app = "sonora-fan"
primary_region = "gru"   # ou "iad", "ams" conforme sua preferência

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  # A chave abaixo pode ser removida se você definir via secrets (recomendado)
  # YOUTUBE_API_KEY = "AIzaSyB--8a_0tAr9Mf2mxy0oWq7rB0qyacci3I"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  path = "/"
  interval = "10s"
  timeout = "2s"
